// <auto-generated />
namespace Coopers.BusinessLayer.Database.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedColumnLatitudeandLongitudetoNetworkLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedColumnLatitudeandLongitudetoNetworkLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201803121131015_Added Column Latitude and Longitude to NetworkLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
