//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coopers.BusinessLayer.Localizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalizer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coopers.BusinessLayer.Localizer.AppLocalizer", typeof(AppLocalizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the PaymentHistory.
        /// </summary>
        public static string ERR_PAYMENTHISTORY_CREATE {
            get {
                return ResourceManager.GetString("ERR_PAYMENTHISTORY_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired! Try re-login again.
        /// </summary>
        public static string ERR_SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("ERR_SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create ChargeOption.
        /// </summary>
        public static string ERR_STRIPECHARGEOPTION_CREATE {
            get {
                return ResourceManager.GetString("ERR_STRIPECHARGEOPTION_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the Notify Account Subscription.
        /// </summary>
        public static string ERR_SUBSCRIPTION_UPDATE {
            get {
                return ResourceManager.GetString("ERR_SUBSCRIPTION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Expired..
        /// </summary>
        public static string ERR_TRANSACTION_EXPIRED {
            get {
                return ResourceManager.GetString("ERR_TRANSACTION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subsciption failed because user might not have sufficient permission..
        /// </summary>
        public static string ERR_UPDATESUBSCRIPTION_RIGHTS {
            get {
                return ResourceManager.GetString("ERR_UPDATESUBSCRIPTION_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifEye.
        /// </summary>
        public static string NotifEye {
            get {
                return ResourceManager.GetString("NotifEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier.
        /// </summary>
        public static string Premier {
            get {
                return ResourceManager.GetString("Premier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration Link.
        /// </summary>
        public static string UserRegistrationLink {
            get {
                return ResourceManager.GetString("UserRegistrationLink", resourceCulture);
            }
        }
    }
}
